version: '3.8'

services:
  placeholder:
    image: nginx:alpine
    container_name: dynia-placeholder
    volumes:
      - /opt/dynia/placeholder/index.html:/usr/share/nginx/html/index.html:ro
      - /opt/dynia/placeholder/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - edge
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  edge:
    external: true